"use strict";
let keyMirror = require('keymirror');

/**
 *
 * @type {Object}
 */
module.exports = keyMirror({
  FOLDER_PUBLISH: 'FOLDER_PUBLISH',
  FOLDER_UNPUBLISH: 'FOLDER_UNPUBLISH',
  FOLDER_UPDATE: 'FOLDER_UPDATE',
  FOLDER_SHOW_FORM: 'FOLDER_SHOW_FORM',
  FOLDER_DELETE: 'FOLDER_DELETE',
  FOLDER_CLONE: 'FOLDER_CLONE',
  FOLDER_CREATE: 'FOLDER_CREATE',
  FOLDER_CREATE_CHILDREN: 'FOLDER_CREATE_CHILDREN'
});