"use strict";
let keyMirror = require('keymirror');

/**
 *
 * @type {Object}
 */
module.exports = keyMirror({
  SEARCH_IN_TREE: 'SEARCH_IN_TREE',
  SET_SELECTED_FOLDER_IDS: 'SET_SELECTED_FOLDER_IDS',
  SET_SELECTED_FOLDERS_IDS_ARR: 'SET_SELECTED_FOLDERS_IDS_ARR',
  CLEAR_SELECTED_FOLDERS_IDS: 'CLEAR_SELECTED_FOLDERS_IDS',
  COPY_MEDIA_TEMPLATES_TO_FOLDER: 'COPY_MEDIA_TEMPLATES_TO_FOLDER',
  DELETE_MEDIA_TEMPLATES: 'DELETE_MEDIA_TEMPLATES'

});